### ISSUE TITLE
File uploading - backend

### ISSUE THREAD

**Issue by michelepistan** [GigiLoria5/se2022-08-HireTracker#1]
Story 2 : Describe hikes

We need to upload a GPX file.
From frontend-side I tried to do it using axios (I don't know if it's the best option, but it's quite popular on the web).

I need to call a backend API to receive this file (for the moment I called it POST /api/uploadFile , but I can change it if necessary)

**Comment by ciaccogiuseppe** [comment]
For sending/receiving the file it should not be a problem from the backend, I don't know how the Axios library works, but in the backend it should be immediate to get the sent file by using express

**Comment by ciaccogiuseppe** [comment]
I'll add the /api/uploadFile also in the backend btw

**Comment by michelepistan** [comment]
Ok perfect

**Comment by ciaccogiuseppe** [comment]
After today's discussion we found it it could be a problem handling 2 API calls in the backend for a single upload (data+file). It could be probably better to handle it in a single API call using multipart/form-data content type

**Comment by ciaccogiuseppe** [comment]
I'll define the api format as soon as possible
