### ISSUE TITLE
[FE] Login/Registration: bugs and Improvements

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#10]
Following manual testing and code review, I identified some issues or improvements in the documentation, code and interfaces style. I list them as a checklist so that you can select them when solved or discussed.

- [x] In the documentation the **route for registration was /signup then in the code you used /register**. I took the liberty of fixing this in the documentation thinking it was a simple mistake, if I missed something please correct it.
- [x] If I press login without having entered anything or only entered the e-mail, **an unclear message comes out**, which a user should not read and could not understand. I think it is better to highlight the fields or set them as required via html or any other solution... except the current one.
![immagine](https://user-images.githubusercontent.com/41837640/201467406-67be0aba-a1b0-4629-8801-f35f96302325.png)
- [x] Displaying messages on there is not very readable, I would recommend displaying errors under the login button or at least near the form. Furthermore, what do you think of a small check that the user enters the e-mail and not anything else?
![immagine](https://user-images.githubusercontent.com/41837640/201467494-6d0f6e1a-3f34-46eb-949a-7a3ca40b19e2.png)
 - [x] When I change pages, the error message does not disappear. This also happen with the welcome message.
![immagine](https://user-images.githubusercontent.com/41837640/201467612-c0b177ab-8bb3-4125-802d-19d4f2a0ce76.png)
- [x] On the logout I would ask you to align it with the design of the interface we have made (first name last name, or email if the former are not present, and next to it the logout button). I think the initial choice is more readable (a button should contain no other information than its action in my opinion).
![immagine](https://user-images.githubusercontent.com/41837640/201467668-e6175b9b-cef7-4696-83b2-3589ac338395.png)
- [x] Emergency operator shuold not have name, surname and phone_number as mandatory
![immagine](https://user-images.githubusercontent.com/41837640/201467792-bf198fc2-016c-4ba7-9aeb-6dac4ea365a6.png)
- [x] The user type "platform manager" is not present in the select box. And a choice I could agree with, but somewhere we have to write it down.
- [x] For the token verification route you should add a page, also just blank with a text ""verified account" and a link back to the login. Because otherwise a page comes out that might confuse the average user
![immagine](https://user-images.githubusercontent.com/41837640/201467913-a5b41c39-9a03-4a5f-9c14-46de8f79cba4.png)
- [x] If the user does not specify the name, messages and writings are blank
![immagine](https://user-images.githubusercontent.com/41837640/201467987-3e9b237d-a8b4-4b87-a6c0-f103ce280bcc.png)

To avoid problems, I recommend working together on the new branch that should now be visible, called 'antosams3_feature_03', and to delete old branches related to this part.

**Comment by antosams3** [comment]
Issues resolved and pushed
