### ISSUE TITLE
Last things before demo 1

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#16]
- [x] the hikes interface needs to be fixed a bit (I'm working on it)
- [x] also the hikes page has some warnings/errors in the console (antonello should be working on that)
- [x] in the db all the default users should be recreated because the hash has changed (we use sha-256)
- [x] in the navbar every now and then there is a glitch in the username which is not aligned or can be seen badly
- [ ] the add hike interface DOES NOT WORK
- [x] "local guide page" does not show on "device mode"
- [x] hikes list does not show up properly on "device mode"
- [x] hike description does not includes author (local guide name+surname that added the hike) and peak altitude
- [x] the private routes for the local guide can be accessed by typing the url

**Comment by ciaccogiuseppe** [comment]
We can merge story3 on dev, then I'll work on recreating users

**Comment by GigiLoria5** [comment]
ok I'll merge now

**Comment by ciaccogiuseppe** [comment]
fixed user db

**Comment by ciaccogiuseppe** [comment]
fixed also local guide page not showing on device mode

**Comment by GigiLoria5** [comment]
I adjusted the interface of hikes a little so that on large screens the filters are displayed on the left side and on smaller screens filters above list below. I removed the see all hikes, because it must be the default action. Everything is on dev

**Comment by GigiLoria5** [comment]
Testing better, however, I noticed that on mobile devices (small screens) the list of hikes is not displayed correctly.

**Comment by ciaccogiuseppe** [comment]
fixed hike list on mobile devices

**Comment by ciaccogiuseppe** [comment]
fixed peak altitude not showing, working on author

**Comment by ciaccogiuseppe** [comment]
fixed author not showing (+ also fixed s2 backend authentication)

**Comment by antosams3** [comment]
Waring and errors removed

**Comment by GigiLoria5** [comment]
fixed _in the navbar every now and then there is a glitch in the username which is not aligned or can be seen badly_

**Comment by GigiLoria5** [comment]
fixed _route protection missing_
