### ISSUE TITLE
Issue #1 - Reset Filters

### ISSUE THREAD

**Issue by MrR0b0t14** [GigiLoria5/se2022-08-HireTracker#18]
For a better user experience would be better not apply filters again after resetting them. It should be something automatic.
Very good work anyway!

**Comment by GigiLoria5** [comment]
We did what was requested. Thanks again for the feedback!

[Demo](https://user-images.githubusercontent.com/41837640/203977474-19da6e9e-3435-46ab-b2da-6bb835f63572.webm)
