### ISSUE TITLE
Peak altitude

### ISSUE THREAD

**Issue by michelepistan** [GigiLoria5/se2022-08-HireTracker#2]
Story 2: Describe hikes

The API POST /api/hikes by Giuseppe requires the field "Peak altitude" that is not present in the form by Estelle. We have to decide if it's a needed field and add it in the frontend, or not and delete it from backend.

**Comment by ciaccogiuseppe** [comment]
Actually peak altitude is not needed as data in the data stored for each hike. Considering it's a value returned by the GET API for hikes, I don't know whether we have to compute it in the backend or set it in the frontend

**Comment by GigiLoria5** [comment]
I simply found this data in the data pool I collected and I think it is very useful information and something users want to know. That is why it is in the database and why it has to be integrated frontend/backend
