### ISSUE TITLE
Logo in navbar displayed incorrectly

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#20]
As someone may have noticed, the logo is only displayed correctly on Firefox, on other browsers it has problems. If anyone can solve it I would be happy
Firefox:
![immagine](https://user-images.githubusercontent.com/41837640/202854806-79bc94ec-2f4e-4ef7-a55f-7cb4277d0149.png)

Chrome, Safari:
![immagine](https://user-images.githubusercontent.com/41837640/202854729-f92def5f-1bbf-416d-aa1f-6788a9556b8f.png)

**Comment by ciaccogiuseppe** [comment]
Fixed it regenerating the svg file, I'll open a pull request for it as soon as possible
