### ISSUE TITLE
Geographical info in hike creation

### ISSUE THREAD

**Issue by ciaccogiuseppe** [GigiLoria5/se2022-08-HireTracker#21]
When a local guide creates an hike, there's a country-province-city 
Should we consider them already present in the DB and select them like in the filter page or can the local guide freely write them (even if not correct)?

**Comment by ciaccogiuseppe** [comment]
https://www.npmjs.com/package/country-state-city we'll check this

**Comment by GigiLoria5** [comment]
They cannot be considered already present in the DB. A local guide should be able to add a new existing (country/province/city) but we must pay attention to don't have wrong written entries
