### ISSUE TITLE
Usability Discussion about Story 2

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#28]
I would have suggestions for improving the interface of story 2, which I believe has several usability/consistency problems although it is still a good interface.

## Form Part 1
1) This might be a personal thought: but usually the steps of a form are signalled with '[Breadcrumbs](https://mui.com/material-ui/react-breadcrumbs/)' not with numbers. Something like this:
![immagine](https://user-images.githubusercontent.com/41837640/203718961-1b26ff9e-be61-450e-a809-4e83d351cf34.png)

2) The part for uploading the file has some **spacing problems**. There should be a margin (or some kind of separation) with the form steps (the numbers above I say), then the button is too close to the first text, and instead the file name is too far away.
I also think that a pattern should be used for loading the file, because this does not give me the impression of loading (**unfamiliarity**). Some common patterns we might follow are as follows:
* [UK Pattern](https://design-patterns.service.justice.gov.uk/patterns/upload-files/) 
* [Pattern Found Online](https://ui-patterns.com/uploads/image/file/3758/best_Upload_Files.png)

3) The Start Point and End Point fields should not be visible until the GPX file is loaded simply because this way it becomes clearer which steps to follow. 

4) For example, for this step the responsive version, with all fields stacked on top of each other, is much clearer. Although it has spacing problems.

4) Although it is debatable in this case (but this may be personal taste) that the point fields are parallel, I think it is important to separate the two columns more because it is difficult to distinguish them, it may also be an idea to add a vertical [divider](https://mui.com/material-ui/react-divider/). However, I would like to emphasise that putting them all on one column would also solve the responsive problem (which as I see it at present is not a great achievement). And also here you would give an order to the actions to be followed... and it is only fair that the starting point is filled in first and then the end point (UX Rule: Respect User Flow).

5) As far as the fields themselves are concerned, I think the type should be first in order.

6) I do not understand why the continue and cancel buttons are outside the form frame. Being part of it I think they should not be inside it. As for the buttons, it would make sense to put them to the side. 

## Form Part 2
1) In this second step, the problems are definitely the layout, alignment and length of the fields. In a form it is a great rule to avoid the Z pattern (zig-zag scanning) and so I think it is essential here to put all the fields on one column and make them longer too. 
![immagine](https://user-images.githubusercontent.com/41837640/203724319-27cfa1a5-d30f-40c2-9d70-e67950999584.png)

2) The grouping of common fields is not well understood because the title is not emphasised (just a possible solution). In addition, in general information there is no distinction between what is automatically calculated and what is not and this could disturb the user (they should not be grouped together).

3) The add hike and back buttons are not aligned and again I do not understand why they are outside the form

4) For example, for this step the responsive version, with all fields stacked on top of each other, is much clearer. Although it has spacing problems.

**Comment by GigiLoria5** [comment]
I leave here a website with some common UX tips on forms: https://www.uidesign.tips/blog/top-ui-ux-design-tips-for-better-forms

**Comment by Dayfive5** [comment]
i'm working on your changes in a branch that i called "S2_(again)_for_luigi"
For page one : 
- breadcrumbs ok
- 1 column instead of 2 ok
- buttons in paper ok
- spacings ok
- description after type ok
- form appear only when file uploaded ok
- divider between upload and form for visibility

I have no time left for this task in my budget
If you want to do the upload pattern thing you can (maybe just displaying the map with the track traced on it could be a solution, as it's just a component to add to the code. But i think you're still working on this component for your own tasks so can't do it now).

I'm gonna start the fixes for page 2

**Comment by Dayfive5** [comment]
page 2 
- breadcrumbs ok
- 1 column ok
- spacings ok
- buttons in paper ok
- bigger textfields ok

for the fields already completed, there were disabled and already filled when the user gets on the page, so there's no reason for the user to feel confused. In case, i added a helper text saying that the field was computed automatically on the concerned fields.

the only "problem" left is your map that is not responsive, but i don't know how your component works and where to modify the code to make it responsive.

**Comment by GigiLoria5** [comment]
I think enough changes have been made.
