### ISSUE TITLE
Problems with integration tests story 5

### ISSUE THREAD

**Issue by FedeBel** [GigiLoria5/se2022-08-HireTracker#29]
I tried to do integration tests and I copied the request body from the documentation. When I run the tests of an user with the wrong role or an user not authenticated it works, but if i run a test with wrong fields or all fields correct the status code is 500 instead of 422. The tests are inside test/testHutAdd.js. Maybe something inside the if (user !== undefined && user.role === "local_guide") don't work. If you can have a look.

**Comment by antosams3** [comment]
You have inserted a wrong URL in all the tests, is /huts not /hikes.
I'll fix for you
<img width="532" alt="image" src="https://user-images.githubusercontent.com/73968766/203790344-5fc63e43-fca3-4c68-9aae-2c5c4fbca530.png">
