### ISSUE TITLE
Story 1: Points (start, end, reference) not shown in the GUI after hike uploading 

### ISSUE THREAD

**Issue by antosams3** [GigiLoria5/se2022-08-HireTracker#32]
Even if the DB includes the new reference points created for this hike correctly, they are not shown on the list of hikes both if the user is not logged (story 1) and logged (story 4). 
Maybe it could be just a story 2 branch issue and it can work on dev, **we have to test again when merging.**

![image](https://user-images.githubusercontent.com/73968766/203943483-69934682-6462-44ab-94bc-2a861c6b31b2.png)

**Comment by GigiLoria5** [comment]
The page on which the points will be displayed has not yet been implemented. What you are showing is still the interface from the last sprint (with all its attendant problems)

**Comment by GigiLoria5** [comment]
this problem was overcome after testing the application with @ciaccogiuseppe
