### ISSUE TITLE
Story 2: GUI report and some minor fixes

### ISSUE THREAD

**Issue by antosams3** [GigiLoria5/se2022-08-HireTracker#33]
The report of the gui test is on client/gui_testing including 2 gpx files (examples of the teacher, links are on HikeTracker.pdf slide 5) and a md file describing the steps done. Just few things to fix (maybe some of them are already fixed): 
- [x]  **logo is gone again** (tested both on chrome and safari) but maybe is just because is not merged with logo fix branch of giuseppe. If it is the case, please check this box 
- [x]  **Geographical informations are mandatory but is not reported**, only when clicking add hike an alert tells me that are required. Just add "required" field (@Dayfive5 I saw that you are working on some improvements for story 2, so take this in account)
- [x] I tested with 2 gpxs files, rocciamelone.gpx and 4.gpx both examples of the teacher. With the first no problems at all, **but the second is not read and no fields are extracted from the file**, even if it seems good. 
- [x] If the same user uploads the same hike 2 times including all the same fields, it is added. it could be better having some checks just for the same user to avoid him doing this. 
- [x] Since the user cannot add a new hike if he doesn't have a gpx file, it could be helpful **having a link to a gpx file creator website**  (like https://www.gpxgenerator.com ) for helping users that are not so much into these things. An example
![image](https://user-images.githubusercontent.com/73968766/203967392-bc40443a-8171-4946-8af3-49bdbcb350de.png)
In this way the user can create its own gpx file, download it from the website and then upload it into our platform: this is my suggestion.

**Comment by GigiLoria5** [comment]
Permit me to say that the logo is not a problem, it is just a missed css rule (I have the fix on my branch), so it will be fixed in the merge. If you want to resolve already you should change the following rule inside our css file
```
svg {
    height: auto;
    width: auto
}
```
into this
```
.leaflet-container svg {
    height: auto;
    width: auto
}
```

**Comment by antosams3** [comment]
One suggestion: 

- [ ] Since the user cannot add a new hike if he doesn't have a gpx file, it could be helpful **having a link to a gpx file creator website**  (like https://www.gpxgenerator.com ) for helping users that are not so much into these things. An example
![image](https://user-images.githubusercontent.com/73968766/203967392-bc40443a-8171-4946-8af3-49bdbcb350de.png)

**Comment by ciaccogiuseppe** [comment]
fixed point 2 and 3, working on point 4
also adding suggestion for creating a gpx file

**Comment by ciaccogiuseppe** [comment]
added suggestion for creating gpx

**Comment by ciaccogiuseppe** [comment]
For point 4, checking uniqueness of hikes requires a check on all the gpx files stored in the db (or saving a digest of them to be checked), then checking for all reference points.
Actually two hikes will become different if there's one reference point which is 1cm different from the one saved in the db so it could be tricky to check if hikes are actually different

**Comment by antosams3** [comment]
> For point 4, checking uniqueness of hikes requires a check on all the gpx files stored in the db (or saving a digest of them to be checked), then checking for all reference points. Actually two hikes will become different if there's one reference point which is 1cm different from the one saved in the db so it could be tricky to check if hikes are actually different

Don't worry, it was just a minor thing but since it doesn't have an impact on the real functioning, you can skip this.
