### ISSUE TITLE
Story 2: Code review results

### ISSUE THREAD

**Issue by antosams3** [GigiLoria5/se2022-08-HireTracker#34]
There are still some little things to do:
- [x] update documentation, new routes are missing 
- [x] add some more checks with express (field type validation like isString() for strings, or required fields using Exists() etc..) for /hikes post 
- [x] add some more tests for fields like altitude, city, province, country, ascent etc… ( test if missing, wrong type,...) 

On the front-end part I fixed some little checks that launched warnings: one major was related to SmootherTextField that uses state initialized using props. Since during the first rendering the prop was undefined, it launched errors in the browser console (A component is changing an uncontrolled input to be controlled ....). 
Now it is fixed.

**Comment by ciaccogiuseppe** [comment]
pushed point 1 and 2

**Comment by ciaccogiuseppe** [comment]
pushed point 3
