### ISSUE TITLE
Story 5: Code Review

### ISSUE THREAD

**Issue by FedeBel** [GigiLoria5/se2022-08-HireTracker#35]
I updated the documentation for some API and there are some things that i found when I tested the application:

- [x] I tryed to start on writing "Italy" inside the country field, then i selected the country "Italy" and sometimes the Region/Province didn't appeared and, instead, it displayed "no options".
- [x] The field "altitude" and "beds number" accept negative numbers 

There is another little thing, that I don't know if it is a problem or not: when i click on the reset button in the second page of "add Hike", I returned to the first page and also the fields here are reset.

For what concern the warnings, I saw these:
![Warning](https://user-images.githubusercontent.com/101119750/204064199-1c2d4fb9-6f15-4e31-ae01-98905b33c375.jpg)

The first one when I am in the main page and the second one when I click on the country field

**Comment by antosams3** [comment]
For what about the first error (download the image  from manifest) I think it is related to logo issue and will be solved when merging with a logo fix branch.
I'll fix negative numbers constraints  both on db and front end right now

**Comment by antosams3** [comment]
@FedeBel I discovered that altitude can be negative, some examples https://www.quora.com/Can-the-altitude-reading-be-negative. I'll fix just the beds number

**Comment by FedeBel** [comment]
Ah ok perfect

**Comment by antosams3** [comment]
Popper warning removed, reset button function was intentional to reset everything and came back to the previous screen so we dont'have to fix it, error about the image is still there since the last sprint, and it is caused by not existing favicons. 
The fix for warning also solves the problem of displaying "no options" sometimes, since it was overlapping elements.
