### ISSUE TITLE
Story 2 - Small (no-core) Improvements

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#39]
Trying to insert a hike revealed some potential improvements:

- [x] show in the ref points table at the top the last one inserted
- [x] implement a draggable reference point marker because it is a bit annoying to do undo every time you place a point in a wrong position
- [x] if from step two I do go back, I don't find the things I had put in before. This problem arises from the choice of making the two form steps in two separate routes (from the point of view of how React is used, this choice is completely incorrect). The suggestion is to handle everything in one route.

_Since we do not have much time left, we could leave them as improvements to be added to the next sprint. The only one that I think might be some kind of bug is the third one. If it wasn't fixed maybe it wouldn't be worth showing during the demo._

**Comment by Dayfive5** [comment]
i'm going to see if i can fix the 3rd point with my time left

**Comment by GigiLoria5** [comment]
@Dayfive5 I found with @antosams3 the problem for the 3rd point. I updated the description

**Comment by Dayfive5** [comment]
i started trying to do as they did in story 5 but I exceeded my time left for this sprint so I won't be able to fix it (I can commit & push on the branch I created and started working on but it's not finished nor working)...

**Comment by Dayfive5** [comment]
if no one has time to fix this, maybe we should replace the go back by a cancel button (and this one would directly go back to the local guide page) for the demo, and then fix this in the next sprint

**Comment by GigiLoria5** [comment]
I think there are other more important problems. A lot of code would have to be changed to solve it, I think it would be wiser to solve it in the next sprint. I keep the issue open...

Maybe in the demo we don't account for it too much 😆

**Comment by ciaccogiuseppe** [comment]
currently working on this issue

**Comment by ciaccogiuseppe** [comment]
point 1 fixed

**Comment by ciaccogiuseppe** [comment]
point 2 fixed

**Comment by ciaccogiuseppe** [comment]
point 3 fixed

**Comment by GigiLoria5** [comment]
resolved by @ciaccogiuseppe
