### ISSUE TITLE
Story 5 - Small (no-core) Improvements

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#42]
I  leave here some small unresolved problems that we will definitely fix in the next sprint

- [ ] If you go back from step two, the country, province and city information is lost
- [ ] After clicking on 'add hut', another 'ok' button should not pop up... in the future it will go to the page where the huts are shown, but just return it to the 'Platform Content' page for now could be much better
- [ ] The telephone number field is maybe too small, it should at least be made as wide as the others

**Comment by FedeBel** [comment]
I added a new unresolved problem:

- [ ] You can create a new hut even if the field of the phone number is empty
