### ISSUE TITLE
[Story 7-BE] Improvements needed

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#71]
### Validation
In the following endpoints the input validation is missing:
 - [x] GET `/api/huts/provinces/:country`
 - [x] GET `/api/huts/cities/:province`
 - [x] GET `/api/huts/filters?...`

### Documentation
In the following endpoints the documentation related to responses is incomplete:
 - [x] GET `/api/huts/countries`
 - [x] GET `/api/huts/provinces/:country`
 - [x] GET `/api/huts/cities/:province`

In the following endpoint is not clear why hut_type is repeated two times, and how this endpoint should be called to filter huts with more or less hut types:
 - [x] GET `/api/huts/filters?city=value&province=value&country=value&altitude_min=value&altitude_max=value&beds_number_min=value&beds_number_max=value&hut_type=value&hut_type=value`

### Dao Implementation
- [x] For purely visibility and user experience issues, it is requested to sort the list of huts according to the most recently (descending ID) added so that this action does not have to be performed on the front-end.  

### Routes Implementation
- [x] **At line 103 of routes/Hut.js the possible hut types are hard-coded.** This list of types should be obtained from a function inside the Hut model to achieve greater flexibility and facilitate future changes. The same problem occurs with line 157, although it is not part of the newly written code, please standardise the source of that information.
- [x] **The function handleHutType should not receive hutTypes as a parameter** as it is a 'constant', rather they should be retrieved within the function itself with a call to a hut model method (as described before).
- [x] On line 141, **n requests, where n is the number of huts, are made to the database to obtain the author's name**. This solution turns out to be poorly performing, think of having 500 huts in the db, the database would be called 500 times to get query names. It is recommended to modify the query for obtaining huts so that with a join, the required author information is obtained directly. The latter will then obviously be merged into one field separately from the query as done in line 142.
- [x] _The same author problem occurs in GetHutById but here the problem is not critical and can therefore be ignored._

### Backend Unit Testing
- [x] The functions handleHutType and handleRangeFilters in the file 'Utils_hut.js' must be tested at unit level. Arrange with @antosams3 for who should do this.

### FE API Function not clear
- [x] In **the function getHutsWithFilters, it is not clear how the parameter is to be passed.** Please add a description of it, in particular to understand what properties are required and how hut_types should be passed as it possibly has multiple values.

**Comment by antosams3** [comment]
- [x] Add checks on ranges values (max should be greater then min and viceversa. Ex. now it returns 200 if max < min )
