### ISSUE TITLE
Point Consistency Check glitchy

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#81]
As known the current API is not the best and sometimes it leads to problems in selecting the correct geographical description

**Comment by ciaccogiuseppe** [comment]
As suggested during planning, a possible solution could be using geonames api, directly or with geocoder-geoname / Geode nodejs libraries

**Comment by antosams3** [comment]
I tried to use geonames, but the reverse function is not available for Italy as you can see here ... http://www.geonames.org/maps/addresses.html#countries
So we have to find another solution

**Comment by ciaccogiuseppe** [comment]
I think we could use the http://api.geonames.org/findNearbyPlaceNameJSON to get country-province-city as before and leave the address fill-in to the local gude

**Comment by ciaccogiuseppe** [comment]
This is a call example with lat = 45.070312 and lng = 7.6868565
![immagine](https://user-images.githubusercontent.com/79985527/209190820-f9fcc542-ddc1-4104-9875-426d257ee8fe.png) @antosams3

**Comment by antosams3** [comment]
Works kinda well with big cities, but if you try to use in small suburbs it doesn't tell you even the province... as you can see
http://api.geonames.org/findNearbyPlaceNameJSON?lat=44.96468969785761&lng=7.2839462757110605&username=hiketracker

The city should be San Pietro VaL Lemina 
I'm looking for another solution

**Comment by ciaccogiuseppe** [comment]
I actually forgot we were working for provinces and not for regions
after you get data from the first query you can youse the hierarchy api with the geonameId found in the first one and it will give you correct data
http://api.geonames.org/hierarchyJSON?geonameId=8972953&username=hiketracker

**Comment by ciaccogiuseppe** [comment]
Province should be in hierarchy level before city 
![immagine](https://user-images.githubusercontent.com/79985527/209408746-d41b6676-01a2-4efb-9656-00fc94ea5739.png)

**Comment by ciaccogiuseppe** [comment]
Province is found in the hierarchy and it should be (at least in this case)
level 3 region
level 4 province
level 5 city 
subsequent levels should be for fractions
while level 0 1 and 2 are for planet, continent, country

**Comment by ciaccogiuseppe** [comment]
![immagine](https://user-images.githubusercontent.com/79985527/209409006-793b465f-6fac-47cb-a752-c6ec0ee0d66f.png)

**Comment by antosams3** [comment]
In the meanwhile I found this website (I registered to have a key to make api calls) that seems to work fine... Just to avoid making 2 api calls 
https://api.geoapify.com/v1/geocode/reverse?lat=45.056323090303465&lon=7.0037841796874&apiKey=cd8f1ca442004fad894cd6f352714cba
