### ISSUE TITLE
[Story 17 & 18/FE] Improvements & Fixes

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#88]
After the review I have found some possible improvements to enhance the general style of the new page and improve the UX.
- [x] There is too much distance between the navbar and the first text of the page. The space should be the same as on the pages of the site. In the following image it is clear the difference between the new page (on the left) and "hikes" (on the right)
![immagine](https://user-images.githubusercontent.com/41837640/209443126-a9919bce-5832-4b6c-8f35-ab04dd2da224.png)
- [x] There is also too much distance between the title and the form that is later shown
![immagine](https://user-images.githubusercontent.com/41837640/209444158-2ddd1c4c-18f6-494d-9d2b-790d9d78d9bf.png)
- [x] The 'form' shown to start a hike does not look very pleasant. I think the problems are this box which I don't find much use for, the title of the hike should be in the same style as a title (bold) but I would even merge it with the actual title (like "START HIKE: HIKE NAME") and then the "Go Back" should be outside this box as it is not a strictly related action but is a safe exit (if you remove the outer box it's fine as positioning)
- [x] The page and its form do not display information clearly and intuitively when a hike is in progress. Even here I would say that the box in which they are enclosed is useless as well as unattractive (at least for me), the title of the hike is relevant information and therefore should be as before in bold, but even here I would join the title that among other things still shows "Start a Hike" despite having already been started, so a possible title is "ONGOING HIKE: HIKE NAME" so you can also remove the words "in progress ..." also unpleasant. Furthermore, I don't understand why displaying the information of when it was started in the form of a test "Hike started at...", much better to use the datepicker again with the label "Start Timer" as before in READONLY mode and without the START button of course. Finally, I would suggest changing the label of the STOP button to TERMINATE (as described by the stakeholder in the story) and then at least to me CANCEL HIKE is not clear, I would write more TERMINATE WITHOUT SAVING (or something similar) in red style as it is a "dangerous" action. 
![immagine](https://user-images.githubusercontent.com/41837640/209444168-6f8d5038-cd17-486b-8df3-192b7f0fefc0.png)
- [x] I believe that the additional feedback showing the info of the hike that has just been completed is unnecessary as the list of completed hikes is present on the same page as the action is completed, and therefore the feedback itself will be the appearance of the new hike in that list.
![immagine](https://user-images.githubusercontent.com/41837640/209444928-24b3e7e1-b4b2-4691-b048-a503f5411455.png)

Finally, I also identified some fixes needed:
- [x] In the documentation the description of the new route is missing
- [x] There is a warning to fix
![immagine](https://user-images.githubusercontent.com/41837640/209443537-668065e7-82d9-47e1-a976-b6c783b05e5c.png)
- [x] The API getActiveActivityByHikeId logs out an error each time an action is performed
![immagine](https://user-images.githubusercontent.com/41837640/209443569-7c49d3ad-5ec1-4739-be0f-6c089bbcc085.png)
- [x] If I start a hike, and then return to the 'my hikes' page, it is no longer shown 
[Demo](https://user-images.githubusercontent.com/41837640/209444666-ec18e911-3616-406a-aa58-59d499d93c6e.webm)
- [x] It is possible to start a hike, even though there is already one running. This must not be possible at all. It is also a problem in the BE as the database is updated... Consider disabling 'START THIS HIKE' or at least turning it into something like 'AN HIKE IS ALREADY ONGOING' with a simple redirect to the new page without changing info. Everything except the current behaviour.
[Demo](https://user-images.githubusercontent.com/41837640/209444777-cbb38a6d-57ba-49b8-800d-5125c5162d84.webm)
- [x] When I 'cancel' a hike, it returns me to the page of the hike I cancelled, why? I would make it stay on the current page so that it also gives feedback that it is finished without saving.
[Demo](https://user-images.githubusercontent.com/41837640/209445298-e81c8b18-cca1-4283-9e80-8a640a5cb2b2.webm)

**Comment by antosams3** [comment]
- Some of the issues you find regarding myHikes page are because, for what I see, it shows the list of the completed hikes and not of the running, so you have to choose if display also the running hike
- For what about the fact of having more hikes running in the same time, I just make the check for the same hike (to not have the same hike running more times), but It's right having only one possible running hike, so I have to change that.

**Comment by GigiLoria5** [comment]
@antosams3 for what regards your first point I disagree because as you can see from the upper 4th point the hike in progress is shown, but only right after it is started, if you reload the page or if you navigate to another page and then come back there, the information is lost (even though into the db there is still). So the problem must be that the "ongoing hike" has been saved only locally with variables/states without getting it from the db (if any).

For the second point, I don't understand if you mean that for you is not possible to run the same hike multiple times over the time or at the same time (which make sense to not be possible)?

**Comment by antosams3** [comment]
For the second point I meant that I just check if the same hike was not running multiple time for the same user, in this way if the user wanted to run it again he has first to terminate it and then it is possible to start again, but in this way the same user can have more hikes running at the same time, and that's wrong... in this morning i'll fix backend issues

**Comment by GigiLoria5** [comment]
Ok, perfect

**Comment by antosams3** [comment]
I managed to do something like this:
If the current hike is running, the start hike button will became this
<img width="383" alt="image" src="https://user-images.githubusercontent.com/73968766/209545870-7146e052-a81e-4d76-a653-8f2834efb93a.png">
If instead the user selects another hike that is not the one he is running, this will appear:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/73968766/209545937-d701f544-9d3d-4304-9095-a2d9022d5401.png">
And then, if the user is not running any hike, the button will be the green one (start hike).

**Comment by GigiLoria5** [comment]
Definitely a better solution. Perhaps the only thing is that the writing in the second case is hardly legible, but that could be a problem with the photo. You can certainly judge it better from the page

**Comment by ciaccogiuseppe** [comment]
Fixes should be all in s17_18 be branch
Tell me if I made something wrong or missed some points

**Comment by antosams3** [comment]
I just made some little changes on the new commit (clean DB, align text center when no hikes have been done, enable GO BACK button that wasn't working)

**Comment by GigiLoria5** [comment]
Last things I found:
- [x] The title of the form is still not at the same distance as the titles of the other pages
- [x] The Go Back button should not be red as it is not a dangerous action but rather white and green like the 'Return Hikes List' button. Also as a matter of compliance
- [x] Since the start has now been moved to a central position, it now makes sense to place the secondary action (Go Back) to the left of it, as done on all other pages. By the way, this is the same thing that was done with 'Delete Hike'.
- [x] When I load a hike page you initially see the button appear and then change appearance. This should not be visible but only be shown when all the content is
![immagine](https://user-images.githubusercontent.com/41837640/209721129-b1b3cd9f-8449-45fa-9248-1602ba37fc20.png)
- [x] The buttons need a slightly higher margin, at least to have the same distance that the two time pickers have.
![immagine](https://user-images.githubusercontent.com/41837640/209721796-54441cb7-ce75-4bb0-99d8-c60658e6da86.png)
- [x] As for the button to terminate the activity without saving, I think it is really tedious and unclear to use 'delete'. If you really can't find an alternative at this point, it was better to leave cancel as it was originally done. Definitely delete is no good.
- [x] I like the idea of the popup to confirm the cancellation of the hike. However, the back should have the same style as the other backs, like green and white 'return hikes list'. And even here, the word delete must not appear because it can imply something else.
![immagine](https://user-images.githubusercontent.com/41837640/209721987-bfb2bec8-bb75-48cb-8691-8b8f80b2702e.png)
- [x] There are still some errors in the console
![immagine](https://user-images.githubusercontent.com/41837640/209721330-60b13d9b-17aa-4ff0-a19c-de1694317c81.png)
- [x] There are new warnings in the terminal
![immagine](https://user-images.githubusercontent.com/41837640/209721421-b9215d25-5ff4-4f8c-8abf-1c0c22a561db.png)

**Comment by ciaccogiuseppe** [comment]
Fixed issues

**Comment by GigiLoria5** [comment]
Now the interfaces are ok. The only problem is that there are still warnings into the terminal and an error in the console
![immagine](https://user-images.githubusercontent.com/41837640/209825217-8116a72d-c00c-4fd5-a829-e6d01bedd13e.png)
![immagine](https://user-images.githubusercontent.com/41837640/209825237-d4132515-7b51-45ed-9ff6-a09e6fd6bdea.png)

**Comment by GigiLoria5** [comment]
When you fix these problems, you can close the issue

**Comment by ciaccogiuseppe** [comment]
I'll fix them soon

**Comment by ciaccogiuseppe** [comment]
All warnings should be removed now
The console one was from the HikeDetail component, now it should work correctly
