### ISSUE TITLE
Time filter displaying problem in Hikes page

### ISSUE THREAD

**Issue by Dayfive5** [GigiLoria5/se2022-08-HireTracker#92]
I added this hike in the branch feature_add_hikes_estelle :
![image](https://user-images.githubusercontent.com/64085258/209548046-44180eaa-593c-4027-8d1c-2ffaf1a1aa72.png)
and now when we are on the hikes page there's that:
![image](https://user-images.githubusercontent.com/64085258/209548176-6bd9851c-b4de-4b87-9712-d436f61b64e9.png)

The time filter should not go outside of the box on the left.

**Comment by GigiLoria5** [comment]
I pushed a possible fix in your branch

![immagine](https://user-images.githubusercontent.com/41837640/209554298-8643811f-bf00-4628-8429-89b4224362eb.png)
