### ISSUE TITLE
Hikes list and buttons colors

### ISSUE THREAD

**Issue by Luca-Rota** [GigiLoria5/se2022-08-HireTracker#99]
As I pointed out today during the meeting the page of hikes, is absolutely not user friendly: there is too much text, all with too similar sizes and with the same color. For a user the page would be boring and there is no element that captures his attention, you should instead provide a few essential information, perhaps accompanied by icons that capture attention. 
Moreover, within the entire application there is too low a variety of colors, which could confuse the user: it is not acceptable that "logout" button, "start hike" button, "return" button, "go back" button, and "login" button and perhaps others, are all green. 
I would therefore suggest that you keep only essential and quick information in the hike list and use some extra color inside the application, such as blue for the "login" button or red for the "logout" button and for the "back" buttons.

**Comment by GigiLoria5** [comment]
Thanks for the feedback Luca. However, your talk about few colours has no basis at all and I guess it is very subjective to you. In the web design community and those who have respect for the usability of their users, there is a rule to always use the same colours for buttons: a primary colour for the main action (in our case green) and a secondary colour for the secondary action (in our case white), with the added colours used only to trigger particular actions (red = danger, etc.). 
The user is confused if he sees a rainbow of colours on the web page and is unable to see a harmony. In fact, always in the guidelines/principles of web development there is written to have "colours applied throughout a UI consistently and be compatible with the brand they represent".


Thank you instead for the first part of the feedback, which will certainly help us to improve the web application.
